name: Update Search Index

on:
  push:
    branches:
      - main

jobs:
  update-search-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run search index script
        run: node src/js/generateSearchIndex.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/search-index.json
          git diff --cached --quiet || git commit -m "Update search-index.json [skip ci]"
          git push