name: Auto Bump Version

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version number
        run: |
          VER=$(cat src/data/version.txt)
          NEW_VER=$(awk '{printf "%.1f", $1 + 0.1}' <<< "$VER")
          echo "$NEW_VER" > src/data/version.txt
          echo "NEW_VER=$NEW_VER" >> $GITHUB_ENV  # Export for next step

      - name: Commit and push new version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add src/data/version.txt
          git diff --cached --quiet || git commit -m "Auto-bump version to $NEW_VER"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}